# Generated by Django 3.1.7 on 2022-01-20 00:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacking',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
